# Generated by Django 5.1.6 on 2025-02-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskTitle', models.CharField(max_length=200)),
                ('taskDescription', models.TextField(max_length=500)),
                ('taskStartDate', models.DateField()),
                ('taskDueDate', models.DateField()),
                ('taskStatus', models.CharField(choices=[('in progress', 'in progress'), ('yet to start', 'yet to start'), ('completed', 'completed')], default='yet to start', max_length=30)),
            ],
        ),
    ]
