# Generated by Django 5.1.6 on 2025-03-03 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskTitle', models.CharField(max_length=200)),
                ('taskDescription', models.TextField(max_length=500)),
                ('taskStartDate', models.DateField()),
                ('taskDueDate', models.DateField()),
                ('taskStatus', models.CharField(choices=[('in progress', 'in progress'), ('yet to start', 'yet to start'), ('completed', 'completed')], default='yet to start', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
