# Generated by Django 5.1.6 on 2025-02-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rollNumber', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.IntegerField()),
                ('address', models.TextField(max_length=200)),
                ('age', models.IntegerField()),
                ('addmissionDate', models.DateField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('classIncharge', models.CharField(max_length=30)),
            ],
        ),
    ]
